mongo:
    host: 185.40.9.190
    port: 27017
    db: data
    driversCollection: driver

server:
    applicationConnectors:
        - type: http
          port: 8280

    adminConnectors:
        - type: http
          port: 8281